// 旅帳 — bilingual copy + data definitions
// Exposed on window for cross-script access.

const COPY = {
  zh: {
    nav: {
      features: "功能",
      how: "使用流程",
      recap: "旅後回顧",
      tech: "技術",
      faq: "FAQ",
    },
    brand: "旅帳",
    brandSub: "Japan Travel Expense",
    hero: {
      badge: "SIDE PROJECT · 2025",
      title1: "一趟日本旅行",
      title2: "所有開銷",
      titleAccent: "一鏡到底",
      sub: "拍張收據，AI 自動辨識店名、品項、稅別；逐條分帳、即時匯率、信用卡回饋——旅行結束還能生成 Spotify Wrapped 風格的回顧卡片。",
      cta1: "立即試用",
      cta2: "查看 GitHub",
      stats: [
        { n: "16", l: "DB Migrations" },
        { n: "50/日", l: "AI 辨識額度" },
        { n: "9+", l: "消費類別" },
        { n: "PWA", l: "可安裝至桌面" },
      ],
    },
    marquee: [
      "AI 收據辨識",
      "Gemini 3 Flash",
      "逐條分帳",
      "即時匯率",
      "信用卡回饋",
      "Supabase Realtime",
      "PWA 離線支援",
      "旅後回顧",
      "Google 登入",
      "Guest 模式",
    ],
    features: {
      eyebrow: "六大核心",
      title: "為日本旅遊量身打造的記帳體驗",
      sub: "每一個功能都來自一趟真實的旅行。從出發前、旅程中、到回家後——旅帳陪你走完全程。",
      items: [
        {
          icon: "auto_awesome",
          tag: "AI",
          title: "拍照即辨識",
          body: "Gemini 3 Flash 自動讀取日文收據：店名、金額、品項、稅別，還翻成繁體中文。每人每天 50 次，夠你一天逛完心齋橋。",
          demo: "ocr",
        },
        {
          icon: "groups",
          tag: "分帳",
          title: "逐條精準分帳",
          body: "不是整張收據一起分。壽司一人一盤、伴手禮幫朋友代墊、房錢均分——每個品項都能獨立指定歸屬。",
          demo: "split",
        },
        {
          icon: "credit_card",
          tag: "信用卡",
          title: "回饋進度追蹤",
          body: "台新 Richart、國泰 Cube 等多張卡切來切去；每卡多方案、共用上限。讓你知道這張還能刷多少錢。",
          demo: "card",
        },
        {
          icon: "insights",
          tag: "即時",
          title: "Dashboard 活著",
          body: "今日花費、旅程累計、預算進度、JPY↔TWD 即時匯率。Supabase Realtime 讓旅伴的消費 0.5 秒後出現在你手機上。",
          demo: "dashboard",
        },
        {
          icon: "celebration",
          tag: "回顧",
          title: "旅後 Wrapped",
          body: "最愛類別、最常造訪的店、最貴一筆、信用卡省了多少——一鍵匯出成圖片，分享到 LINE 或 IG。",
          demo: "recap",
        },
        {
          icon: "install_mobile",
          tag: "PWA",
          title: "無網也能記帳",
          body: "安裝到手機桌面、Guest 模式不用註冊、離線記帳、回家再同步。從 JR 地下鐵到白川鄉深山都用得上。",
          demo: "pwa",
        },
      ],
    },
    how: {
      eyebrow: "使用流程",
      title: "從一張收據到一次旅行的完整紀錄",
      sub: "四個步驟，就這麼簡單。",
      steps: [
        { step: "01", jp: "撮る", title: "拍照上傳", body: "結完帳隨手拍收據。直接開相機或從相簿挑，模糊、折過、反光都能讀。" },
        { step: "02", jp: "分ける", title: "確認分帳", body: "AI 幫你預填欄位。逐條打勾誰付的、誰要分、要不要指定信用卡。" },
        { step: "03", jp: "見る", title: "即時追蹤", body: "Dashboard 秒更新。今日、本趟、回饋進度、匯率換算一目了然。" },
        { step: "04", jp: "分かち合う", title: "旅後分享", body: "回家後生成 Wrapped 風格回顧卡，一鍵匯出圖片傳給旅伴。" },
      ],
    },
    recap: {
      eyebrow: "旅後回顧",
      title: "像 Spotify Wrapped，但給你的錢包",
      sub: "旅行不只是把錢花完。旅帳把每一筆消費變成一張可以分享的故事卡。",
      tripName: "2025 東京 · 京都 9 日",
      cards: [
        { key: "total", title: "總花費", big: "¥287,460", sub: "≈ NT$63,240", note: "共 83 筆消費 · 9 天" },
        { key: "fav", title: "最愛類別", big: "🍜 餐飲", sub: "共 42 筆 · 佔 51%", note: "拉麵 x 12 碗，是不是太多了？" },
        { key: "store", title: "最常造訪", big: "7-ELEVEN", sub: "去了 11 次", note: "早餐、宵夜、關東煮、糰子…" },
        { key: "big", title: "最貴一筆", big: "¥38,500", sub: "HARBS 草莓千層 x 旅伴生日", note: "2025/04/07 表參道" },
        { key: "card", title: "信用卡回饋", big: "NT$2,180", sub: "台新 Richart 海外 2.8%", note: "省下一頓晚餐的錢" },
        { key: "day", title: "最豪氣一日", big: "¥54,300", sub: "2025/04/10", note: "築地早餐 → 銀座午餐 → 歌舞伎町晚餐" },
      ],
    },
    tech: {
      eyebrow: "技術棧",
      title: "Stack",
      sub: "Next.js 16 + React 19 + Supabase + Gemini AI — 完整的全端 TypeScript side project。",
      stack: [
        { cat: "框架", items: ["Next.js 16", "React 19", "TypeScript 5"] },
        { cat: "UI", items: ["Tailwind CSS 4", "shadcn/ui", "Recharts", "Lucide"] },
        { cat: "後端", items: ["Supabase (PG)", "Auth + RLS", "Realtime", "Storage"] },
        { cat: "AI", items: ["Google Gemini 3 Flash", "OCR 用量管控", "日→繁翻譯"] },
        { cat: "功能", items: ["PWA", "html-to-image", "Web Share API", "Google OAuth"] },
        { cat: "部署", items: ["Vercel", "Edge Runtime", "Analytics"] },
      ],
      arch: {
        title: "架構亮點",
        bullets: [
          { k: "雙模式資料層", v: "Guest localStorage + Authenticated Supabase，guest 可無痛遷移至帳號。" },
          { k: "分帳演算法", v: "Greedy 最小化轉帳次數，N 人旅程結算 O(n log n)。" },
          { k: "RLS policy", v: "16 支 migration，每張 table 獨立讀寫策略，避免跨旅程資料洩漏。" },
          { k: "OCR 節流", v: "每人每日 50 次上限，server-side counter + Gemini 快取。" },
        ],
      },
    },
    faq: {
      eyebrow: "FAQ",
      title: "常見問題",
      items: [
        { q: "這是一個正式產品還是 side project？", a: "Side project。起心動念是 2025 自己規劃東京京都行前研究記帳 app 時，覺得市面上沒一個真的懂日本旅遊（多幣別、多人、信用卡回饋）的——所以自己做了一個。" },
        { q: "需要註冊才能用嗎？", a: "不用。打開網站就能用 Guest 模式，資料存在瀏覽器裡。想跟旅伴共享再登入即可，Guest 的資料可一鍵遷移到帳號。" },
        { q: "AI 辨識準嗎？", a: "使用 Google Gemini 3 Flash，對日文收據（便利商店、餐廳、藥妝、百貨）測試準確率 90%+；稅別（內稅/外稅）和品項分行都有處理。" },
        { q: "免費嗎？會不會有 API 爆量？", a: "完全免費。Supabase / Gemini 都用免費額度，OCR 每人每日 50 次上限防爆量，實測一人一天 50 次已經是行程很滿的上限。" },
        { q: "離線能用嗎？", a: "PWA 安裝後可離線記帳（Guest 模式），回到網路再同步。AI 辨識需要網路，但手動輸入永遠可用。" },
        { q: "為什麼專注日本？", a: "因為日本收據格式相對統一、消費類別（餐飲、交通、購物、住宿）對台灣人旅遊很典型，且 JPY↔TWD 匯率需求強。未來可擴展但目前專注做精。" },
      ],
    },
    footer: {
      built: "Built with Next.js 16 · Supabase · Gemini AI",
      copy: "© 2025 旅帳 · 一個給愛去日本的人的 side project",
      cta: "準備好了？",
      ctaSub: "下一趟東京、京都、北海道，讓旅帳陪你記。",
      ctaBtn: "立即開始記帳",
    },
    tweaks: {
      title: "Tweaks",
      theme: "配色主題",
      themes: [
        { key: "sakura", name: "櫻和風", desc: "米白 · 朱紅 · 松葉" },
        { key: "amber", name: "GOSU 琥珀", desc: "深色 · 琥珀黃" },
        { key: "monochrome", name: "極簡黑白", desc: "Apple 風留白" },
      ],
      lang: "語言",
      langs: [{ key: "zh", name: "繁中" }, { key: "en", name: "English" }],
      hero: "Hero 排版",
      heroes: [
        { key: "centered", name: "置中疊字", desc: "直書 + 大標題" },
        { key: "split", name: "左文右機", desc: "iPhone mockup" },
        { key: "editorial", name: "雜誌排版", desc: "大寫 + 網格" },
      ],
      showTech: "顯示技術棧",
    },
  },
  en: {
    nav: {
      features: "Features",
      how: "How",
      recap: "Recap",
      tech: "Stack",
      faq: "FAQ",
    },
    brand: "TabiChō",
    brandSub: "Japan Travel Expense",
    hero: {
      badge: "SIDE PROJECT · 2025",
      title1: "One trip to Japan,",
      title2: "every receipt,",
      titleAccent: "one app.",
      sub: "Snap a receipt. AI reads store, items, tax. Split line-by-line, convert currency live, track credit-card cashback — then get a Spotify-Wrapped-style recap when you fly home.",
      cta1: "Try it live",
      cta2: "View on GitHub",
      stats: [
        { n: "16", l: "DB migrations" },
        { n: "50/day", l: "AI OCR quota" },
        { n: "9+", l: "categories" },
        { n: "PWA", l: "installable" },
      ],
    },
    marquee: [
      "Gemini OCR",
      "Line-item split",
      "Live FX",
      "Cashback tracking",
      "Supabase Realtime",
      "PWA offline",
      "Travel Wrapped",
      "Google OAuth",
      "Guest mode",
      "Open source",
    ],
    features: {
      eyebrow: "Six pillars",
      title: "Built for the way you spend in Japan.",
      sub: "Every feature came from a real trip. From planning to post-trip recap — TabiChō walks the whole route with you.",
      items: [
        { icon: "auto_awesome", tag: "AI", title: "Shoot & read", body: "Gemini 3 Flash parses Japanese receipts — store, yen, items, tax — and translates to traditional Chinese. 50 scans/day, enough for a Shinsaibashi marathon.", demo: "ocr" },
        { icon: "groups", tag: "Split", title: "Line-item split", body: "Not one split for the whole bill. Per dish, per souvenir, per room rate — each item has its own payer and shares.", demo: "split" },
        { icon: "credit_card", tag: "Cards", title: "Cashback progress", body: "Juggle Richart, Cathay Cube and more. Multiple plans per card, shared cap. Always know how much headroom is left.", demo: "card" },
        { icon: "insights", tag: "Live", title: "Dashboard, live", body: "Today's spend, trip total, budget burn, JPY↔TWD live FX. Supabase Realtime pushes your travel buddy's spend to your phone in 500ms.", demo: "dashboard" },
        { icon: "celebration", tag: "Recap", title: "Post-trip Wrapped", body: "Top category, most-visited store, biggest splurge, cashback saved — export the whole thing as an image to share on LINE or IG.", demo: "recap" },
        { icon: "install_mobile", tag: "PWA", title: "Works offline", body: "Install to home screen. Guest mode — no signup. Offline logging, sync on reconnect. From the Yamanote Line to the Shirakawa-go mountains.", demo: "pwa" },
      ],
    },
    how: {
      eyebrow: "How it works",
      title: "From one receipt to a full trip record.",
      sub: "Four steps. That's it.",
      steps: [
        { step: "01", jp: "撮る", title: "Snap", body: "Point your camera at the receipt or pick from album. Blurry, creased, glare — it reads through." },
        { step: "02", jp: "分ける", title: "Split", body: "AI pre-fills everything. Check who paid, who splits, tag a card if any." },
        { step: "03", jp: "見る", title: "Track", body: "Dashboard updates instantly. Today, trip total, cashback progress, FX — all at a glance." },
        { step: "04", jp: "分かち合う", title: "Share", body: "Back home, generate a Wrapped-style recap. Export as image, send to your travel buddy." },
      ],
    },
    recap: {
      eyebrow: "Travel Wrapped",
      title: "Like Spotify Wrapped, for your wallet.",
      sub: "Travel isn't just about spending money. TabiChō turns each receipt into a shareable story card.",
      tripName: "Tokyo · Kyoto · 9 days · 2025",
      cards: [
        { key: "total", title: "Total spend", big: "¥287,460", sub: "≈ NT$63,240", note: "83 receipts · 9 days" },
        { key: "fav", title: "Top category", big: "🍜 Food", sub: "42 receipts · 51%", note: "12 bowls of ramen. Too many?" },
        { key: "store", title: "Most visited", big: "7-ELEVEN", sub: "11 times", note: "Breakfast, late-night snacks, oden…" },
        { key: "big", title: "Biggest splurge", big: "¥38,500", sub: "HARBS cake x birthday", note: "2025/04/07, Omotesandō" },
        { key: "card", title: "Cashback saved", big: "NT$2,180", sub: "Richart 2.8% overseas", note: "Dinner, on the house." },
        { key: "day", title: "Priciest day", big: "¥54,300", sub: "2025/04/10", note: "Tsukiji → Ginza → Kabukichō" },
      ],
    },
    tech: {
      eyebrow: "Stack",
      title: "Stack",
      sub: "Next.js 16 + React 19 + Supabase + Gemini — end-to-end TypeScript side project.",
      stack: [
        { cat: "Framework", items: ["Next.js 16", "React 19", "TypeScript 5"] },
        { cat: "UI", items: ["Tailwind 4", "shadcn/ui", "Recharts", "Lucide"] },
        { cat: "Backend", items: ["Supabase (PG)", "Auth + RLS", "Realtime", "Storage"] },
        { cat: "AI", items: ["Gemini 3 Flash", "OCR quota", "JP→zh-TW"] },
        { cat: "Features", items: ["PWA", "html-to-image", "Web Share API", "Google OAuth"] },
        { cat: "Deploy", items: ["Vercel", "Edge Runtime", "Analytics"] },
      ],
      arch: {
        title: "Engineering highlights",
        bullets: [
          { k: "Dual-mode data", v: "Guest localStorage + authenticated Supabase. One-click migration on sign-in." },
          { k: "Split algorithm", v: "Greedy transfer minimization — O(n log n) settlement for n travelers." },
          { k: "RLS policy", v: "16 migrations, per-table policies, zero cross-trip data leakage." },
          { k: "OCR throttle", v: "Server-side daily counter, 50/user, Gemini cache-friendly." },
        ],
      },
    },
    faq: {
      eyebrow: "FAQ",
      title: "FAQ",
      items: [
        { q: "Is this a real product or a side project?", a: "Side project. Started when I was planning my 2025 Tokyo-Kyoto trip and couldn't find an expense app that actually understood Japan travel (multi-currency, multi-person, cashback-aware). So I built one." },
        { q: "Do I need to sign up?", a: "No. Open the site and use Guest mode — data lives in your browser. Sign in only when you want to share with a travel buddy; your guest data migrates in one click." },
        { q: "How accurate is the AI?", a: "Uses Google Gemini 3 Flash. Tested on JP conbini, restaurant, drugstore and department receipts at 90%+ accuracy. Handles inclusive/exclusive tax and multi-line items." },
        { q: "Is it free? What about API quotas?", a: "Fully free. Built entirely on Supabase and Gemini free tiers. 50 OCR/day per user prevents abuse — empirically more than a packed itinerary needs." },
        { q: "Does it work offline?", a: "Install as PWA, log expenses offline (Guest mode), sync when you're back online. AI OCR needs network; manual entry always works." },
        { q: "Why only Japan?", a: "JP receipts have a stable format, categories (food/transit/shopping/lodging) match typical Taiwanese travel, and JPY↔TWD FX is the primary use case. Expandable later, but focused now." },
      ],
    },
    footer: {
      built: "Built with Next.js 16 · Supabase · Gemini AI",
      copy: "© 2025 TabiChō · A side project for Japan lovers.",
      cta: "Ready?",
      ctaSub: "Your next Tokyo, Kyoto, or Hokkaidō trip — let TabiChō keep the tab.",
      ctaBtn: "Start tracking",
    },
    tweaks: {
      title: "Tweaks",
      theme: "Color theme",
      themes: [
        { key: "sakura", name: "Sakura", desc: "Washi · vermilion · pine" },
        { key: "amber", name: "GOSU amber", desc: "Dark · amber" },
        { key: "monochrome", name: "Mono", desc: "Apple-esque" },
      ],
      lang: "Language",
      langs: [{ key: "zh", name: "繁中" }, { key: "en", name: "English" }],
      hero: "Hero layout",
      heroes: [
        { key: "centered", name: "Stacked", desc: "Tategaki + bold" },
        { key: "split", name: "Split", desc: "Copy + iPhone" },
        { key: "editorial", name: "Editorial", desc: "Grid + caps" },
      ],
      showTech: "Show stack",
    },
  },
};

window.COPY = COPY;
